routes:
  - url: /auth/bearer_token/users/1
    method: GET
    status_code: 200
    response:
      - firstName: jane
        lastName: doe
        id: 1
      - firstName: john
        lastName: doe
        id: 2
    auth:
      bearer_token:
        token: token
  - url: /auth/bearer_token/user
    method: POST
    status_code: 201
    body:
      firstName: foo
      lastName: bar
    response:
      - firstName: foo
        lastName: bar
    auth:
      bearer_token:
        token: tokens
  - url: /auth/bearer_token/user
    method: PUT
    status_code: 201
    body:
      firstName: Foo
      lastName: Bar
    response:
      - firstName: Foo
        lastName: Bar
    auth:
      bearer_token:
        token: tokens
  - url: /auth/bearer_token/user/1
    method: DELETE
    status_code: 200
    auth:
      bearer_token:
        token: token

